// Code generated by mockery v2.32.0. DO NOT EDIT.

package mocks

import (
	model "chart-viewer/pkg/model"

	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// AnalyzeTemplate provides a mock function with given fields: templates, kubeVersion
func (_m *Service) AnalyzeTemplate(templates []model.Template, kubeVersion string) ([]model.AnalyticsResult, error) {
	ret := _m.Called(templates, kubeVersion)

	var r0 []model.AnalyticsResult
	var r1 error
	if rf, ok := ret.Get(0).(func([]model.Template, string) ([]model.AnalyticsResult, error)); ok {
		return rf(templates, kubeVersion)
	}
	if rf, ok := ret.Get(0).(func([]model.Template, string) []model.AnalyticsResult); ok {
		r0 = rf(templates, kubeVersion)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.AnalyticsResult)
		}
	}

	if rf, ok := ret.Get(1).(func([]model.Template, string) error); ok {
		r1 = rf(templates, kubeVersion)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetChart provides a mock function with given fields: repoName, chartName, chartVersion
func (_m *Service) GetChart(repoName string, chartName string, chartVersion string) (error, model.ChartDetail) {
	ret := _m.Called(repoName, chartName, chartVersion)

	var r0 error
	var r1 model.ChartDetail
	if rf, ok := ret.Get(0).(func(string, string, string) (error, model.ChartDetail)); ok {
		return rf(repoName, chartName, chartVersion)
	}
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(repoName, chartName, chartVersion)
	} else {
		r0 = ret.Error(0)
	}

	if rf, ok := ret.Get(1).(func(string, string, string) model.ChartDetail); ok {
		r1 = rf(repoName, chartName, chartVersion)
	} else {
		r1 = ret.Get(1).(model.ChartDetail)
	}

	return r0, r1
}

// GetCharts provides a mock function with given fields: repoName
func (_m *Service) GetCharts(repoName string) (error, []model.Chart) {
	ret := _m.Called(repoName)

	var r0 error
	var r1 []model.Chart
	if rf, ok := ret.Get(0).(func(string) (error, []model.Chart)); ok {
		return rf(repoName)
	}
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(repoName)
	} else {
		r0 = ret.Error(0)
	}

	if rf, ok := ret.Get(1).(func(string) []model.Chart); ok {
		r1 = rf(repoName)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]model.Chart)
		}
	}

	return r0, r1
}

// GetRepos provides a mock function with given fields:
func (_m *Service) GetRepos() []model.Repo {
	ret := _m.Called()

	var r0 []model.Repo
	if rf, ok := ret.Get(0).(func() []model.Repo); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Repo)
		}
	}

	return r0
}

// GetStringifiedManifests provides a mock function with given fields: repoName, chartName, chartVersion, hash
func (_m *Service) GetStringifiedManifests(repoName string, chartName string, chartVersion string, hash string) string {
	ret := _m.Called(repoName, chartName, chartVersion, hash)

	var r0 string
	if rf, ok := ret.Get(0).(func(string, string, string, string) string); ok {
		r0 = rf(repoName, chartName, chartVersion, hash)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetTemplates provides a mock function with given fields: repoName, chartName, chartVersion
func (_m *Service) GetTemplates(repoName string, chartName string, chartVersion string) ([]model.Template, error) {
	ret := _m.Called(repoName, chartName, chartVersion)

	var r0 []model.Template
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, string) ([]model.Template, error)); ok {
		return rf(repoName, chartName, chartVersion)
	}
	if rf, ok := ret.Get(0).(func(string, string, string) []model.Template); ok {
		r0 = rf(repoName, chartName, chartVersion)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Template)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = rf(repoName, chartName, chartVersion)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetValues provides a mock function with given fields: repoName, chartName, chartVersion
func (_m *Service) GetValues(repoName string, chartName string, chartVersion string) (error, map[string]interface{}) {
	ret := _m.Called(repoName, chartName, chartVersion)

	var r0 error
	var r1 map[string]interface{}
	if rf, ok := ret.Get(0).(func(string, string, string) (error, map[string]interface{})); ok {
		return rf(repoName, chartName, chartVersion)
	}
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(repoName, chartName, chartVersion)
	} else {
		r0 = ret.Error(0)
	}

	if rf, ok := ret.Get(1).(func(string, string, string) map[string]interface{}); ok {
		r1 = rf(repoName, chartName, chartVersion)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(map[string]interface{})
		}
	}

	return r0, r1
}

// RenderManifest provides a mock function with given fields: repoName, chartName, chartVersion, values
func (_m *Service) RenderManifest(repoName string, chartName string, chartVersion string, values []string) (error, model.ManifestResponse) {
	ret := _m.Called(repoName, chartName, chartVersion, values)

	var r0 error
	var r1 model.ManifestResponse
	if rf, ok := ret.Get(0).(func(string, string, string, []string) (error, model.ManifestResponse)); ok {
		return rf(repoName, chartName, chartVersion, values)
	}
	if rf, ok := ret.Get(0).(func(string, string, string, []string) error); ok {
		r0 = rf(repoName, chartName, chartVersion, values)
	} else {
		r0 = ret.Error(0)
	}

	if rf, ok := ret.Get(1).(func(string, string, string, []string) model.ManifestResponse); ok {
		r1 = rf(repoName, chartName, chartVersion, values)
	} else {
		r1 = ret.Get(1).(model.ManifestResponse)
	}

	return r0, r1
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
